#!/bin/bash

AFFINE_TRANSFORM=$1
DEFORMATION_FIELD=$2
REFERENCE_IMAGE=$3
MOVING_IMAGE=$4
OUTPUT_IMAGE=$5

export DIM=3
WarpImageMultiTransform \
    $DIM \
    ${MOVING_IMAGE} \
    ${OUTPUT_IMAGE} \
    ${DEFORMATION_FIELD} \
    ${AFFINE_TRANSFORM} \
   -R ${REFERENCE_IMAGE}

